In [1]:
pip install tensorflow

In [2]:
import tensorflow as tf

# Step 1: Create matrix A using random_normal
A = tf.random.normal(shape=(2, 2))
print("Matrix A:\n", A)

# Step 2: Create matrix B using truncated_normal
B = tf.random.truncated_normal(shape=(2, 2))
print("Matrix B:\n", B)

# Step 3: Create matrix C using random.normal with mean=2 and stddev=0.1
C = tf.random.normal(shape=(2, 2), mean=2, stddev=0.1)
print("Matrix C:\n", C)

# Step 4: Perform matrix addition A + B and store the result in D
D = tf.add(A, B)
print("Matrix D (A + B):\n", D)

# Step 5: Perform matrix multiplication C * D and store the result in E
E = tf.matmul(C, D)
print("Matrix E (C * D):\n", E)

Matrix A:
 tf.Tensor(
[[ 0.54638994 -0.18373139]
 [-1.541067   -0.17257476]], shape=(2, 2), dtype=float32)
Matrix B:
 tf.Tensor(
[[ 1.209704   -0.11185267]
 [ 0.02318727 -0.8189688 ]], shape=(2, 2), dtype=float32)
Matrix C:
 tf.Tensor(
[[1.8826077 2.0611537]
 [2.0231788 2.0703888]], shape=(2, 2), dtype=float32)
Matrix D (A + B):
 tf.Tensor(
[[ 1.756094   -0.29558405]
 [-1.5178797  -0.99154353]], shape=(2, 2), dtype=float32)
Matrix E (C * D):
 tf.Tensor(
[[ 0.17745256 -2.6001923 ]
 [ 0.41029096 -2.6509    ]], shape=(2, 2), dtype=float32)


Let's proceed with the tasks using TensorFlow:

Create a matrix F with dimensions 2x2, initialized with random values using TensorFlow's random_uniform function.

Calculate the transpose of matrix F and store the result in matrix G.

Calculate the element-wise exponential of matrix F and store the result in matrix H.

Create a matrix I by concatenating matrix F and matrix G horizontally.

Create a matrix J by concatenating matrix F and matrix H vertically.

Here's the code to perform these tasks:

In [3]:
import tensorflow as tf

# Step 1: Create matrix F using random_uniform
F = tf.random.uniform(shape=(2, 2))
print("Matrix F:\n", F)

# Step 2: Calculate the transpose of matrix F and store the result in G
G = tf.transpose(F)
print("Matrix G (Transpose of F):\n", G)

# Step 3: Calculate the element-wise exponential of matrix F and store the result in H
H = tf.exp(F)
print("Matrix H (Element-wise exponential of F):\n", H)

# Step 4: Create matrix I by concatenating matrix F and G horizontally
I = tf.concat([F, G], axis=1)
print("Matrix I (Concatenation of F and G horizontally):\n", I)

# Step 5: Create matrix J by concatenating matrix F and H vertically
J = tf.concat([F, H], axis=0)
print("Matrix J (Concatenation of F and H vertically):\n", J)


Matrix F:
 tf.Tensor(
[[0.91577995 0.66393924]
 [0.6803143  0.987972  ]], shape=(2, 2), dtype=float32)
Matrix G (Transpose of F):
 tf.Tensor(
[[0.91577995 0.6803143 ]
 [0.66393924 0.987972  ]], shape=(2, 2), dtype=float32)
Matrix H (Element-wise exponential of F):
 tf.Tensor(
[[2.4987233 1.942429 ]
 [1.9744983 2.6857822]], shape=(2, 2), dtype=float32)
Matrix I (Concatenation of F and G horizontally):
 tf.Tensor(
[[0.91577995 0.66393924 0.91577995 0.6803143 ]
 [0.6803143  0.987972   0.66393924 0.987972  ]], shape=(2, 4), dtype=float32)
Matrix J (Concatenation of F and H vertically):
 tf.Tensor(
[[0.91577995 0.66393924]
 [0.6803143  0.987972  ]
 [2.4987233  1.942429  ]
 [1.9744983  2.6857822 ]], shape=(4, 2), dtype=float32)
